### home
GET http://localhost:5000/

### obtener productos
GET http://localhost:5001/productos

### agregar productos
POST http://localhost:5001/productos
Content-Type: application/json

{
    "nombre": "libro",
    "cantidad": 2,
    "precio": 20
}


### modificar productos
PUT http://localhost:5001/productos/8
Content-Type: application/json

{
    "nombre": "libro",
    "cantidad": 2,
    "precio": 20
}

### eliminar productos
DELETE http://localhost:5000/productos/3

### obtener un producto
GET http://localhost:5000/productos/2

### filtrar productos
GET http://localhost:5000/productos?filtro=libro

